backend:
  name: git-gateway
  branch: main
  site_url: https://skillwill.netlify.app

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "settings"
    label: "Site Settings"
    editor:
      preview: false
    files:
      - name: "global"
        label: "Global Settings"
        file: "content/settings/global.json"
        fields:
          - { label: "Site Name", name: "site_name", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image" }
