backend:
  name: git-gateway
  branch: main
  site_url: https://skillwill.netlify.app

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
