backend:
  name: github
  repo: gerasik/Skillwill
  branch: main
  auth_endpoint: https://gerasik.github.io/Skillwill/admin/oauth/authorize

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
